---
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Build .tgz for Apache Cassandra
run-name: "cassandra-tag: ${{ inputs.cassandra-tag }}. tag: ${{ inputs.tag }}. Run #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      cassandra-tag:
        description: "Apache Cassandra tag to build"
        required: true
        default: "cassandra-5.0.4"
      tag:
        description: "Tag name to create"
        required: true
        default: "cassandra-5.0.4-patched"
      forceCreate:
        type: boolean
        description: "Force tag creation"
        required: false
        default: true
      target-ref:
        description: "Target branch in qubership-cassandra-operator repo (default: main)"
        required: true
        default: "main"
      replace-symbol:
        description: "Symbol to change '/' in ref name to"
        required: true
        default: "_"
permissions:
  contents: write

env:
  CASSANDRA_TAG: ${{ inputs.cassandra-tag }}
  REPLACE_SYMBOL: ${{ inputs.replace-symbol }}
  TAG: ${{ inputs.tag }}
  TARGET_REF: ${{ inputs.target-ref }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Create a New Tag ${{ env.TAG }}
        uses: netcracker/qubership-workflow-hub/actions/tag-action@8c6dbeb901920bae9f40d7d7b646d8d9127e1ce7 # v2.4.0
        with:
          ref: ${{ github.ref_name }}
          tag-name: ${{ env.TAG }}
          force-create: ${{ inputs.forceCreate }}
          switch-to-tag: true
          create-release: true
          draft-release: false
          skip-checkout: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: |
          rm -rf ./*

      - name: "Checkout Cassandra tag ${{ env.CASSANDRA_TAG }}"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: apache/cassandra
          ref: ${{ env.CASSANDRA_TAG }}

      - name: Checkout cassandra-patches tag ${{ env.TAG }}
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ env.TAG }}
          path: ./cassandra-patches

      - name: Apply patches
        run: |
          cd ${GITHUB_WORKSPACE}
          for p in ./cassandra-patches/cassandra-patches/${{ env.CASSANDRA_TAG }}/*.patch; do
            echo "Applying $p…"
            git apply -p1 --ignore-space-change --ignore-whitespace "$p"
          done
          rm -rf ./cassandra-patches        

      - name: Setup JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: adopt
          java-version: 11
      - name: Setup JDK
        run: |
          # Skip installing pacakge docs {makes the man-db trigger much faster)
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF
          sudo apt install -y openjdk-11-jdk
          jdk_path=$(update-java-alternatives --list | grep "java-1.11." |awk '{print $3}')
          sudo update-java-alternatives --set ${jdk_path}
          export JAVA_HOME=${jdk_path}
          echo "JAVA_HOME=${jdk_path}" >> $GITHUB_ENV
          echo "JAVA_HOME=${JAVA_HOME}"
          java -version
      - uses: cedx/setup-ant@da941eb444b657ea183d731ba96e59ec26411014 # v6.3.0
        with:
          optional-tasks: false
          version: ">=1.10.0"
      - name: build
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          sed -i '/property name="version"/s/-SNAPSHOT/-patched/g' ./build.xml 
          chmod +x ./.build/build-artifacts.sh
          ./.build/build-artifacts.sh
        env:
          CASSANDRA_DIR: ${{ github.workspace }}

      - name: "Upload files"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          include-hidden-files: true
          path: ${{ github.workspace }}/build/apache-cassandra-*.tar.gz
          name: apache-cassandra

      - name: "Upload assets"
        if: success()
        uses: netcracker/qubership-workflow-hub/actions/assets-action@8c6dbeb901920bae9f40d7d7b646d8d9127e1ce7 # v2.4.0
        with:
          tag: ${{ env.TAG }}
          item-path: build/apache-cassandra-*.tar.gz, NEWS.txt, NOTICE.txt, ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # https://github.com/Netcracker/cassandra-patches/releases/download/cassandra-5.0.8-patched/apache-cassandra-5.0.8-patched-bin.tar.gz
      - name: Set vars for repository dispatch event
        run: |
          CASSANDRA_DISTRO=$(find build/ -regextype posix-extended -regex '.*/apache-cassandra-[0-9.-]+bin\.tarr\.gz' | head -n 1 | xargs -I {} basename {})
          if [ -f "core/build/distributions/$CASSANDRA_DISTRO" ]; then
            echo "Found Cassandra distribution: $CASSANDRA_DISTRO"
            echo "CASSANDRA_DISTRO=$CASSANDRA_DISTRO" >> $GITHUB_ENV
          else
            echo "Cassandra distribution not found!"
            exit 1
          fi
          CASSANDRA_VERSION=${CASSANDRA_TAG#cassandra-}
          echo "CASSANDRA_VERSION=$CASSANDRA_VERSION" >> $GITHUB_ENV

      - name: Trigger repository dispatch event
        uses: netcracker/qubership-workflow-hub/actions/custom-event@8c6dbeb901920bae9f40d7d7b646d8d9127e1ce7 # v2.4.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: qubership-cassandra-operator
          event-type: cassandra-patched-build
          client-payload: '{"cassandra-version": "${{ env.CASSANDRA_VERSION }}", "cassandra-distro": "${{ env.CASSANDRA_DISTRO }}", "cassandra-distro-url": "https://github.com/${{ github.repository_owner }}/cassandra-patches/releases/download/${{ env.TAG }}/${{ env.CASSANDRA_DISTRO }}", "target-ref": "${{ env.TARGET_REF }}", "replace-symbol": "${{ env.REPLACE_SYMBOL }}", "tag": "${{ env.TAG }}", "repo":"${{ github.repository }}"}'
